# Generated by Django 3.0.8 on 2020-07-12 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('value', models.PositiveIntegerField(verbose_name='value')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
            options={
                'verbose_name': 'production',
                'verbose_name_plural': 'productions',
            },
        ),
        migrations.AddConstraint(
            model_name='production',
            constraint=models.UniqueConstraint(fields=('timestamp', 'location'), name='unique_production'),
        ),
    ]
